name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: build-and-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: npm ci --prefer-offline --no-audit

      - name: Build
        run: npm run build

      - name: List dist
        run: |
          echo "----- DIST ROOT -----"
          ls -la dist
          echo
          echo "----- DIST/ASSETS -----"
          ls -la dist/assets || echo "dist/assets NÃO ENCONTRADO"
          echo
          echo "----- FIND (.js/.css/.html) -----"
          find dist -maxdepth 2 -type f \( -name "*.js" -o -name "*.css" -o -name "*.html" \) -print

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-build
          path: dist

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}       # br362.hostgator.com.br
          username: ${{ secrets.FTP_USERNAME }}   # HB@poster.flaviobrick.com.br
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21

          # sua conta FTP já entra em /HB, então "/" publica dentro de HB
          local-dir: dist/
          # depois (forçando a pasta do subdomínio)
          server-dir: /poster.flaviobrick.com.br/HB/

          dangerous-clean-slate: true
          log-level: verbose
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.map
